"""Bake FLE's Lua tool library into the open_world scenario's control.lua.

Why: FLE injects its library (functions + event handlers) over RCON at runtime.
A late-joining Factorio client rebuilds its Lua state from save + scenario files
only, so its handler set can't match the server's -> "mod event handlers are not
identical" join refusal. Baking the identical source into control.lua gives
every joiner the same functions and handler registrations at load time; FLE's
runtime injections then merely re-define the same things (broadcast to all
peers, so live clients stay consistent too).

Preconditions (already patched in this venv's FLE install):
  - library lives in plain globals fle_actions/fle_utils (never in `storage`,
    which must stay serialisable)
  - every script.on_event / script.on_nth_tick registration is top-level and
    unconditional (dynamic registration breaks the join handler check)

Order mirrors FLE's injection order (last-wins matters for the on_tick handler
that both utils.lua and alerts.lua register):
  checksum -> initialise -> tools (server.lua last per dir) -> init_scripts list
"""

from pathlib import Path

FLE = Path(__file__).parent / ".venv/lib/python3.12/site-packages/fle"
MODS = FLE / "env/mods"
TOOLS = FLE / "env/tools"
OUT = FLE / "cluster/scenarios/open_world/control.lua"

# instance.py's explicit init_scripts order (after initialise + tools)
INIT_SCRIPTS = [
    "lualib_util",
    "utils",
    "alerts",
    "connection_points",
    "recipe_fluid_connection_mappings",
    "serialize",
    "serialize_direction_fix",
]


def ordered_files():
    files = [MODS / "checksum.lua", MODS / "initialise.lua"]

    # every valid tool dir (has server.lua + client.py), all lua, server.lua last
    for server in sorted(TOOLS.rglob("server.lua")):
        d = server.parent
        if not (d / "client.py").exists():
            continue
        luas = sorted(p for p in d.glob("*.lua") if p.name != "server.lua")
        files.extend(luas)
        files.append(server)

    for name in INIT_SCRIPTS:
        files.append(MODS / f"{name}.lua")

    # sanity: mods dir must contain exactly what we bake (an uninjected extra
    # baked in would give joiners MORE handlers than the server has)
    baked_mods = {f.name for f in files if f.parent == MODS}
    on_disk = {p.name for p in MODS.glob("*.lua")}
    extra = on_disk - baked_mods
    if extra:
        raise SystemExit(f"mods dir has files FLE does not inject: {extra} - resolve before baking")

    missing = [f for f in files if not f.exists()]
    if missing:
        raise SystemExit(f"missing lua files: {missing}")
    return files


def main():
    files = ordered_files()
    parts = [
        "-- AUTO-GENERATED by bake_scenario.py - do not edit by hand.",
        "-- FLE tool library baked into the scenario so multiplayer late-join works.",
        'util = require("util")',
        "fle_actions = fle_actions or {}",
        "fle_utils = fle_utils or {}",
        'log("FLE-BAKE: control.lua loaded, library + handlers registered")',
    ]
    for f in files:
        rel = f.relative_to(FLE)
        parts.append(f"\n-- ======== {rel} ========")
        # each file runs as its own chunk, exactly like an RCON injection does
        # (keeps file-level `local`s scoped and permits trailing `return`s)
        parts.append(";(function()")
        parts.append(f.read_text().rstrip())
        parts.append("end)();")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"baked {len(files)} files, {OUT.stat().st_size} bytes -> {OUT}")


if __name__ == "__main__":
    main()
